name: news
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.6.0
  get_it: ^8.2.0
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  talker_bloc_logger: ^5.0.0
  provider: ^6.1.5
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  email_validator: ^3.0.0
  timeago: ^3.7.1
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^16.0.1
  image_picker: ^1.2.0
  image_cropper: ^10.0.0
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
